package com.jtd.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_base_user","user_id",User.class);
		arp.addMapping("t_base_permission","permission_id",SysPermission.class);
		arp.addMapping("t_base_role","role_id",SysRole.class);
		arp.addMapping("t_base_user_role","user_role_id",SysUserRole.class);
		arp.addMapping("t_base_role_permission","role_permission_id",SysRolePermission.class);
		arp.addMapping("t_receipt", "receipt_id", Reciept.class);
		arp.addMapping("t_base_process","process_id",Process.class);
		arp.addMapping("t_advice", "advice_id", Advice.class);
	}
}

